Fix wake

diff --git a/.github/workflows/wake_render.yml b/.github/workflows/wake_render.yml
--- a/.github/workflows/wake_render.yml
+++ b/.github/workflows/wake_render.yml
@@ -11,9 +11,9 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Send HTTP request to wake the server
-        with:
+        env:
           COMPANY_ID: ${{ secrets.COMPANY_ID }}
           WORKSPACE_ID: ${{ secrets.WORKSPACE_ID }}
           TOKEN: ${{ secrets.TOKEN }}
-        run: |
-          curl -H 'Authorization: Bearer "$TOKEN"' -X 'GET' 'https://fs19-pm-be-java.onrender.com/"$COMPANY_ID"/"$WORKSPACE_ID"' || echo "Failed to wake server"
+          run: |
+            curl -H "Authorization: Bearer $TOKEN" -X GET "https://fs19-pm-be-java.onrender.com/$COMPANY_ID/$WORKSPACE_ID" || echo "Failed to wake server"
